// Autogenerated changelog
const APP_CHANGELOG = {
  version: "1.0.3",
  releaseDate: "2026-06-20",
  points: [
    "Added profile isolation and data encryption for secure PIN-protected profiles.",
    "Restricted secondary auto-backup configurations to active profiles.",
    "Integrated custom verification PIN prompts on sensitive settings.",
    "Fixed connection offline check and auto-updater workflow release permissions."
  ]
};
