// Autogenerated changelog for v1.2.2
const APP_CHANGELOG = {
  "version": "1.2.2",
  "releaseDate": "2026-06-21",
  "points": [
    "Implemented automatic app closure and auto-relaunch update workflow after updates download."
  ]
};
