// Autogenerated changelog for v1.0.7
const APP_CHANGELOG = {
  "version": "1.0.7",
  "releaseDate": "2026-06-20",
  "points": [
    "feat: check facebook page and accumulate changelog entries during release",
    "fix: format welcome version title string with v prefix stuck to version number",
    "feat: move welcome modal version badge to title and clean up checkbox footer"
  ]
};
