/**
 * Release Automation Script
 * Bumps the version in package.json, commits, tags, pushes, and publishes to GitHub.
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const packageJsonPath = path.join(__dirname, '../package.json');

// Read package.json
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const currentVersion = packageJson.version;

// Determine next version (default to patch bump)
let nextVersion = process.argv[2];

if (!nextVersion) {
  const parts = currentVersion.split('.');
  if (parts.length === 3) {
    const patch = parseInt(parts[2], 10);
    parts[2] = (patch + 1).toString();
    nextVersion = parts.join('.');
  } else {
    console.error(`Error: Current version ${currentVersion} is not in semver format X.Y.Z`);
    process.exit(1);
  }
}

console.log(`Current version: ${currentVersion}`);
console.log(`Target next version: ${nextVersion}`);

function runCmd(cmd) {
  console.log(`Executing: ${cmd}`);
  try {
    execSync(cmd, { stdio: 'inherit' });
  } catch (error) {
    console.error(`Command failed: ${cmd}`);
    process.exit(1);
  }
}

// 1. Update package.json
packageJson.version = nextVersion;
fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n', 'utf8');
console.log(`Updated package.json to version ${nextVersion}`);

// 2. Git operations
runCmd('git add .');
runCmd(`git commit -m "release: prepare release v${nextVersion}"`);
runCmd(`git tag -a v${nextVersion} -m "Release v${nextVersion}"`);

// 3. Push to GitHub
console.log('Pushing commit and tag to GitHub...');
runCmd('git push origin main');
runCmd(`git push origin v${nextVersion}`);

// 4. Create Draft Release on GitHub using GitHub CLI (with autogenerated notes)
console.log('Creating draft release on GitHub with autogenerated release notes...');
runCmd(`gh release create v${nextVersion} --draft --generate-notes`);

// 5. Build and Publish Release Assets
console.log('Building and publishing the release assets to GitHub...');
runCmd('npm run publish');

// 6. Make the Release Public/Stable
console.log('Publishing the draft release to make the update live...');
runCmd(`gh release edit v${nextVersion} --draft=false`);

// 7. Generate Facebook Post Template
console.log('Generating Facebook Post description...');
const facebookPostPath = path.join(__dirname, `../dist/facebook-post-v${nextVersion}.txt`);

let changelogPoints = '';
try {
  const tags = execSync('git tag --sort=-v:refname', { encoding: 'utf8' }).trim().split('\n');
  const currentTag = `v${nextVersion}`;
  const previousTag = tags.find(t => t !== currentTag && (t.startsWith('v') || t.match(/^\d/)));
  
  if (previousTag) {
    const rawLog = execSync(`git log ${previousTag}..HEAD --oneline`, { encoding: 'utf8' }).trim();
    changelogPoints = rawLog.split('\n')
      .map(line => '  • ' + line.replace(/^[a-f0-9]+\s+/, ''))
      .join('\n');
  }
} catch (e) {
  changelogPoints = '  • General performance and security improvements.';
}

const facebookPostContent = `📢 E-Class Record Update: Version v${nextVersion} is now LIVE! 🚀

We are excited to announce the release of E-Class Record v${nextVersion}! This update brings key features, optimizations, and improvements to your local teacher class record app.

🌟 What's New in this Version:
${changelogPoints || '  • General performance and security improvements.'}

💻 How to Get the Update:
• For New Users: Download the latest setup installer directly from GitHub:
  👉 https://github.com/jerniqz-del/eclassrecord/releases/download/v${nextVersion}/E-Class-Record-Setup-${nextVersion}.exe

• For Existing Users: No need to reinstall! Simply open your app, go to Settings, and click "Check for Updates" to install the update instantly!

Thank you for using E-Class Record! Help your fellow teachers by sharing this post! 🧑‍🏫👩‍🏫

#EClassRecord #DepEd #GradingSheet #TeacherLife #EdTech #Update #TeacherTools
`;

fs.writeFileSync(facebookPostPath, facebookPostContent, 'utf8');

console.log(`\n======================================================`);
console.log(`🎉 FACEBOOK POST GENERATED: ${facebookPostPath}`);
console.log(`======================================================\n`);
console.log(facebookPostContent);
console.log(`======================================================\n`);
console.log(`Successfully bumped version, pushed to GitHub, and published Release v${nextVersion}!`);
